package com.steplabs.edgeplayerbackend.DynamoDBModels;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.steplabs.edgeplayerbackend.model.Audit;
import lombok.*;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "posts")
public class Post extends Audit {

    @DynamoDBHashKey(attributeName = "postId")
    @DynamoDBAutoGeneratedKey
    private String postId;

    @DynamoDBAttribute(attributeName = "smallDescription")
    private String smallDescription;

    @DynamoDBAttribute(attributeName = "bigDescription")
    private String bigDescription;

    @DynamoDBAttribute(attributeName = "postPic")
    private String postPic;

    @DynamoDBAttribute(attributeName = "postUrl")
    private String postUrl;

    @DynamoDBAttribute(attributeName = "likes")
    private int likes;

    @DynamoDBAttribute(attributeName = "comments")
    private int comments;

    @DynamoDBAttribute(attributeName = "userId")
    private String userId;

    @DynamoDBAttribute(attributeName = "userName")
    private String userName;

    @DynamoDBAttribute(attributeName = "proPic")
    private String proPic;





}
